---
name: 'Run aspell'
author: limakzi
description: 'Run `aspell` to check spelling.'

branding:
  icon: 'book'
  color: 'purple'

inputs:
  files:
    description: 'Files which to run `aspell` on. Supports glob patterns.'
    required: false
    default: '**/*.tex'
  args:
    description: 'Arguments passed to `aspell`.'
    required: false
    default: '--lang=en_GB --mode=tex'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '${{ inputs.files }}'
    - '${{ inputs.args }}'
