---
name: Continuous Integration

on:
  pull_request:
  schedule:
    - cron: '15 18 * * 0'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Test Action
        uses: ./
        with:
          files: 'test/**/*.md'
          args: '--lang=en --mode=markdown'
