---
name: Continuous Integration

on:
  pull_request:
  schedule:
    - cron: '15 18 * * 0'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        text: [markdown, tex]
        lang: [pl, de, en]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Test Action
        uses: ./
        with:
          files: 'test/${{ matrix.text }}/${{ matrix.lang }}/**'
          args: '--lang=${{ matrix.lang }} --mode=${{ matrix.text }}'
